### PR TITLE
Minor bug fixes and adjustments.

### PR DESCRIPTION
**Pull request by cslux**
Changes:
- Return lexicographical sorted list in `helm--make-target-list-qp`
- Use stricter regex in `helm--make-target-list-qp` (Previous did return targets which aren't targets)
- Remove `or` statement, as it is not required with the new regex
- Search for '# Make data base.*\n' to determine if the output of `make -qp` is valid

### CODE REVIEW

**Comment by abo-abo** [comment]
I don't agree with the regex: a target can be any file name - it can include `.` or `_`. Could you correct the regex? Otherwise the change is fine.

**Comment by cslux** [comment]
> I don't agree with the regex: a target can be any file name - it can include . or _. Could you correct the regex?

I will! I made a test with the emacs Makefile which is pretty complex and it gives incorrect results.  
I'll implement something tomorrow after work, that matches the bash completion output.

**Comment by cslux** [comment]
Ok, I think this should be fine now and sorry for the delay!

**Changes:**
- Return lexicographical sorted list in helm--make-target-list-qp
- Use stricter regex in helm--make-target-list-qp (Previous did return
  targets which aren't targets)
- Use looking-at instead of looking-back which caused massive
  performance issues

**Comment by abo-abo** [comment]
Thanks a lot. I've tested it only a very small amount, hopefully it works fine in complex cases.

**Comment by cslux** [comment]
Well I tested it on some bigger projects like Emacs, QT etc.. In fact it was even more accurate than the bash  completion on Fedora, where I got occasionally some directories as candidates. But you never know ;-)

**Pull request merged**
