### PR TITLE
MOD: Changed the functionality of helm-make-projectile.

### PR DESCRIPTION
**Pull request by cslux**
helm-make-projectile will first look in projectile-project-root followed
by projectile-project-root/build for a makefile.
If helm-make-build-dir is set it will first look there for a makefile.

Also updated the DOCSTRINGS.

### CODE REVIEW

**Comment by abo-abo** [comment]
Is the point of the commit to just extend `helm-make-build-dir` from a string to a list of strings?  In that case, it can be simplified by a lot.

**Comment by cslux** [comment]
> Is the point of the commit to just extend helm-make-build-dir from a string to a list of strings? In that case, it can be simplified by a lot.

Correct! 

However, I just wanted to avoid, that the user has to set the buffer-local variable helm-make-build-dir for the case where he/she builds the project out of source. Almost all project I work on are build out of source (in build), and many other do too. 

So I thought it would be a good idea to look for a makefile there by default, without the need to set any variable. 

Adding a customizable (not buffer-local) variable which holds a list to look for a makefile in projectile-project-root would also be a solution.

**Comment by abo-abo** [comment]
> Almost all project I work on are build out of source (in build), and many other do too.

So we could search in `projectile-root/Makefile` and `projectile-root/build/Makefile` in that order, in case `helm-make-build-dir` isn't set.  When it's set, it takes priority (just gets moved to the front of the above 2-item list). Is that a good solution?

**Comment by cslux** [comment]
Oleh Krehel writes:

>> Almost all project I work on are build out of source (in build), and many other do too.
>
> So we could search in `projectile-root/Makefile` and `projectile-root/build/Makefile` in that order, in case `helm-make-build-dir` isn't set.  When it's set, it takes priority (just gets moved to the front of the above 2-item list). Is that a good solution?
>
That's how I have implemented it write now, but I'm sure it can be simplified.

**Comment by abo-abo** [comment]
Please check the new implementation. I like using `cl-find-if` here, I think it makes it look more simple.

**Comment by cslux** [comment]
Looks good to me. By the way could you please tell me what those thinks like ` | , | .@` at 
[lines 155-156](https://github.com/abo-abo/helm-make/blob/master/helm-make.el#L155-L156) are called. Thank you!

**Comment by abo-abo** [comment]
See [info/elisp/Evaluation/Backquote](http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html).
Basically it's a shorthand for `list`, `cons` and stuff - *very* convenient.

**Comment by cslux** [comment]
> See [info/elisp/Evaluation/Backquote](http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html).
> Basically it's a shorthand for `list`, `cons` and stuff - *very* convenient.

Thank you.

**Comment by cslux** [comment]
Sorry for being so pedantic, but I have declared the variable `helm-make-build-dir` with an empty string. 
Now
``` emacs-lisp
(if (stringp helm-make-build-dir)
    ....
  )
```
at [line 156](https://github.com/abo-abo/helm-make/blob/master/helm-make.el#L156) always yields to `t`. Means we should declare it with an initial value of `nil`.

PS: I think we have hit a bug in helm. Helm preselects install/strip when the `car` of `helm-make-target-history` is "all", instead of "all". I'll file a bug for that on the helm issue tracker.

**Comment by abo-abo** [comment]
> at line 156 always yields to t. Means we should declare it with an initial value of nil.

It's not a big deal, it that case the search path becomes '("" "" "build"), which is OK since the first Makefile found will be used anyway. I want to keep the default one as a string, since it's declared like that in `defcustom`. I think the case when `helm-make-build-dir` is a list will be rare.

> I think we have hit a bug in helm. Helm preselects install/strip when the car of helm-make-target-history is "all", instead of "all"

Well `install/strip` does match `all`. Although Ivy has a special case of always preselecting a perfect match, so maybe Helm should have that too.

**Comment by cslux** [comment]
>> at line 156 always yields to t. Means we should declare it with an initial value of nil.
>
> It's not a big deal, it that case the search path becomes '("" "" "build"), which is OK since the first Makefile found will be used anyway. I want to keep the default one as a string, since it's declared like that in `defcustom`. I think the case when `helm-make-build-dir` is a list will be rare.

Make sense to me.

>> I think we have hit a bug in helm. Helm preselects install/strip when the car of helm-make-target-history is "all", instead of "all"
>
> Well `install/strip` does match `all`. Although Ivy has a special case of always preselecting a perfect match, so maybe Helm should have that too.

Right, will report the issue to them.

**Pull request closed without merging**
