### PR TITLE
Build regexp for candidate preselect

### PR DESCRIPTION
**Pull request by xuchunyang**
@cslux can this fix your issue posted in https://github.com/emacs-helm/helm/issues/1115?

### CODE REVIEW

**Comment by cslux** [comment]
Partly!

When I change [line 120](https://github.com/abo-abo/helm-make/blob/master/helm-make.el#L120) to
```
:preselect (concat "\\_<" (regexp-quote  (car helm-make-target-history)) "\\_>")))
```
Than "all" would be selected correctly, but would fail so when the previous input was "cl", where helm would select the target "clear", but preselect selects "default_target".

**Comment by cslux** [comment]
@xuchunyang  `ivy` always preselects the correct target so it isn't necessary to change it.

**Comment by xuchunyang** [comment]
Right, just removed the change about `ivy`.

**Comment by xuchunyang** [comment]
You are right, because `:history` in helm is the input history, not the real candidate.

**Comment by xuchunyang** [comment]
Is it acceptable if we just use initial input and give up preselect? Otherwise, we need to make that history manually for helm or maybe try to use low-level `helm-comp-read` instead of `helm`.

**Comment by cslux** [comment]
> Is it acceptable if we just use initial input and give up preselect?

Well, that's how I have implemented initially but we decided to just preselect the target  (see https://github.com/abo-abo/helm-make/pull/8).

**Comment by xuchunyang** [comment]
Try to use `helm-comp-read` now, should work soon.

**Comment by cslux** [comment]
Right helm-comp-read is the way to go.

**Comment by xuchunyang** [comment]
`helm-comp-read` will build a source for history, but the history can only be one element, I think it is bug of `helm-comp-read`, if this works fine, using a source for history is possible way (compare to preselect). So now, if you still want to use preselect, manage that history list manually for helm.

**Comment by xuchunyang** [comment]
I've built history manually when using helm completion method, it should works now.

**Comment by cslux** [comment]
@xuchunyang  Unfortunately this doesn't work either.

**Comment by xuchunyang** [comment]
oop, forget to build a  stricter regexp for `:preselect` in helm.

**Comment by xuchunyang** [comment]
I hope it should work now.

> The only problem right now is that ivy stores the input from the minibuffer rather than the chosen target, as helm and ido do.

I don't know about `ivy`, but maybe you can also try to build history by yourself like 84e42a3 did for helm.

**Comment by cslux** [comment]
But actually that looks quite good now.

**Comment by cslux** [comment]
> Nope, maybe (format "^%s$" (car helm-make-target-history), otherwise if getting "foo" it can't distinguish "foobar" and "foo"

Yep, you are right.

**Comment by cslux** [comment]
@xuchunyang 

I made some slightly modification to it. Now all completion back-ends behave the same. And also solves the problem that `ivy` adds the actual input (minibuffer) to the variable `helm-make-target-history` instead of the executed target. This means that now `helm-make-target-history` holds nothing than the target names, as it was planned.  
See https://github.com/cslux/helm-make/commit/2389168b7db1c3179301c9167fd99b2e20854475

**Comment by abo-abo** [comment]
Please check if the accepted change works. I don't support building the history manually: there's a clear interface for it to be automatic.

**Comment by cslux** [comment]
Sorry to say that, but it still doesn't behave like I wanted. 

I'm made some tests based on the latest commit which describes the currently behaver and the desired one. Here the link to the commit -> https://github.com/cslux/helm-make/commit/c41fb7ff0bac7eb1d23b6716e9717a37ad21e290#diff-4b12b0c749c56cff7e9eeb06f441f4bcR138

Sorry for the inconvenience.

**Comment by abo-abo** [comment]
I don't really agree on the history/desired history thing.  Suppose I made the input "stall" and chose "install" out of the two options (install/uninstall).

Then it makes sense to put "stall" on the history, so that when I type <kbd>M-p</kbd>, the input will be "stall", and the candidate list will be "install"/"uninstall". With Ivy, the candidate index is actually put on the history as a string property, so even though there are two candidates for "stall", always the proper one should be preselected.

If the other completion methods don't support that - well they should, since it's nicer for the user: you still get to recall the last candidate with <kbd>M-p RET</kbd>, but you also get to see what other options match your input, since they matched it the last time you called the command.

On the other hand, I don't want to be unreasonable: if Helm or Ido can't support the feature that I described, feel free to open a PR that treats the history in a simple way only for Helm and Ido - leave Ivy as it is.

**Comment by cslux** [comment]
Right, it wouldn't provide you than uninstall. Also helm would put "stall" on the history list, except ido wouldn't as described  in my commit. Just wanted to make sure that you get the same behaviour for all completion methods. Besides, I thought it would be better to store the recently executed targets. 

Howsoever, I will leave `ivy` as it is (do not touch the history :-), and will look for a solution for helm and/or ido only. 

Nevertheless, we still should force, that the input matches a candidate for `helm` and `ido` too. I will open PL request for that.

**Pull request closed without merging**
